version: "3.3"
   
services:
  db:
    image: postgres
    container_name: Psql
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - .:/.env
  web:
    build: .
    container_name: dockerweb
    command: bash start.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
